apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/{{.ORG}}/{{.APP_NAME}}:{{.VERSION}}"
  artifacts:
    - image: changeme
      context: .
      docker: {}
  local: {}
deploy:
  kubectl: {}
profiles:
  - name: dev
    build:
      artifacts:
        - image: 'dev/asciinema-viewer'
          context: .
          docker: {}
      local:
        push: false
      tagPolicy:
        envTemplate:
          template: 'dev/asciinema-viewer:{{.USER}}'
    deploy:
      helm:
        releases:
          - name: asciinema-viewer
            chartPath: charts/asciinema-viewer
            setValueTemplates:
              image.repository: 'dev/asciinema-viewer'
              image.tag: '{{.USER}}'